group 'com.example.tradplus_sdk'
version '1.0'



buildscript {
    repositories {
        flatDir {
            dirs 'libs'
        }
        google()
        mavenCentral()
        mavenLocal()

    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        flatDir {
            dirs 'libs'
        }


    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    namespace "com.example.tradplus_sdk" // <- 必须加上

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 23
    }
}

def TRADPLUS_VERSION = "16.4.0.1"

dependencies {
    //TradPlus
    compileOnly "com.tradplusad:tradplus:${TRADPLUS_VERSION}"
    compileOnly 'com.quality-ad:uid2-adapter:1.0.1'
    compileOnly 'com.tradplusad:tradplus-tool:1.1.4'

}